import{a as b,S as L,i as c}from"./assets/vendor-iB-pPhnc.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const w="55384494-f2f10e06cce2d01ce9b41eadb",S="https://pixabay.com/api/";async function y(o,a=1){const t={key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15};return(await b.get(S,{params:t})).data}const q=new L(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const a=document.querySelector(".gallery"),t=o.map(r=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${r.largeImageURL}">
        <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${r.likes}</p>
        <p><b>Views</b> ${r.views}</p>
        <p><b>Comments</b> ${r.comments}</p>
        <p><b>Downloads</b> ${r.downloads}</p>
      </div>
    </li>`).join("");a.insertAdjacentHTML("beforeend",t),q.refresh()}function v(){document.querySelector(".gallery").innerHTML=""}function m(){document.querySelector(".loader").style.display="block"}function h(){document.querySelector(".loader").style.display="none"}function g(){document.querySelector(".load-more-btn").style.display="block"}function d(){document.querySelector(".load-more-btn").style.display="none"}const f=document.querySelector(".form"),x=document.querySelector(".load-more-btn");let i="",s=1,u=0;f.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.currentTarget.elements["search-text"].value.trim(),i===""){c.error({message:"Please enter a search query!"});return}s=1,v(),d(),m();try{const t=await y(i,s);if(u=t.totalHits,t.hits.length===0){c.error({message:"Sorry, no images found!"});return}p(t.hits),u>15&&g()}catch(t){console.error(t)}finally{h(),f.reset()}});x.addEventListener("click",async()=>{s+=1,d(),m();try{const o=await y(i,s);p(o.hits),typeof lightbox<"u"&&lightbox.refresh();const a=Math.ceil(u/15);s>=a?(d(),c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results.",messageColor:"#FFFFFF",backgroundColor:"#EF4040",theme:"dark"})):g();const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}catch(o){console.error(o)}finally{h()}});
//# sourceMappingURL=index.js.map
